name = "IndEco"
uuid = "60007217-ccd6-4f20-a69a-21f04036fe1c"
authors = ["GodotMisogi <GodotMisogi@github.com> and contributors"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
